version: "3.7"

services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=redis
    volumes:
      - "./data:/home/docker/data"
    networks:
      - redis-node

  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=redis-node
      - POSTGRES_PASSWORD=redis-node
      - POSTGRES_DB=redis-node
    volumes:
      - pgdata:/data/postgres
    networks:
      - redis-node

  server:
    build: .
    container_name: redis-node
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      - redis-node

volumes:
  pgdata:
    driver: local

networks:
  redis-node:
    name: redis-node
    driver: bridge
